//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyMVCCVsitesi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hobiler
    {
        public int ID { get; set; }
        public string Hobi1 { get; set; }
        public string Hobi2 { get; set; }
    }
}
